name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    - name: Install Tauri CLI
      run: cargo install tauri-cli
    
    - name: Build application
      run: cargo tauri build --target x86_64-pc-windows-msvc
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/LogWhisper_*.msi
          src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/LogWhisper_*.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
